### ISSUE TITLE
UI Bugs with target alpha 13.3

### ISSUE THREAD

**Issue by image-et-son** [image-et-son/p600fw#103]
1) When started in preset mode the loaded preset directly received the display dot as if the sound was edited --> FIXED

2) In preset mode changing the arp/seq speed shows up as a dot in the diplay as if the preset was changed (which it is not, since the speed is not stored in the patch) --> FiXED

3) In preset patch mode: when the last pot to be touched is the data pot pressing From Tape will immediately apply the current data pot value and load that patch --> FIXED

4) Sometimes when entering preset mode that prestet changed dot appears. There is no apparent pattern to this.

**Comment by matrix12x** [comment]
Compiled 7079a0e
On boot into preset mode I'm still getting a "dot" in the display. (Bug)

If I enter manual mode and then go back into preset mode there is no "dot." (seems ok)

**Comment by image-et-son** [comment]
That's one stubborn bug. I fixed it but then I needed to change something very close by...

**Comment by el-folie** [comment]
> 

Can confirm Matrix12x´ description.

**Comment by el-folie** [comment]
alpha 13.4
1, The dot when booting in preset mode seems to be gone here. Booted a few times in panel/preset mode. Confirmed.

4. The dot randomly appearing when entering preset mode is still happening. No pattern to it.

**Comment by matrix12x** [comment]
I confirm that the dot is not there
